version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-football-club
        ports:
            - "9000:9000"
        restart: always
        working_dir: /var/www
        volumes:
            - ../app:/var/www
        networks:
            - football-club
        depends_on:
            - mysql
    nginx:
        build:
            context: .
            dockerfile: NginxDockerFile
        container_name: nginx-football-club
        links:
            - php
        restart: always
        ports:
            - "8050:80"
        volumes:
            - ../app:/var/www
        networks:
            - football-club
    mysql:
        image: 'mysql:8.0'
        container_name: mysql-football-club
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: 'football-club'
            MYSQL_USER: 'football-club'
            MYSQL_PASSWORD: 'football-club'
            MYSQL_ROOT_PASSWORD: 'qwerty123'
        networks:
            - football-club

networks:
    football-club:


